import pygame
import random

# ------ CONSTANTS ------

# Colors
WHITE = (255, 255, 255)
BLUE = (0, 0, 255)
PURPLE = (255, 0, 255)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)
GREEN = (0, 255, 0)
BLACK = (0, 0, 0)

# ------ GAME OPTIONS ------

WIDTH, HEIGHT = 1080, 720
MINIGAME_WIDTH = WIDTH - 100
MINIGAME_HEIGHT = HEIGHT - 100
FRAMERATE = 60

FONT_SIZE = 36
PLAYER_TIPS_FONT_SIZE = 15
FONT_COLOR = WHITE

PLAYER_TIP_SHOW_TIME_MS = 4000
PLAYER_INTERACTION_COOLDOWN_MS = 200
PLAYER_SPEED = 500
BULLET_SPEED = 1500
BOULDER_SPAWN_INTERVAL_MS = 1500
BULLET_COOLDOWN_MS = 300
ROCKET_LIVES = 3

MAX_ALIEN_GROWTH = 5
VIRUS_GROWTH_KILL = 10
VIRUS_GROWTH_COOLDOWN_MS = 20000
VIRUS_GROWTH_DISPLAY_MSG_TIME_MS = 5000

PLATE_UNLOCK_COMBINATION = ["3", "1", "5", "2", "4"]

# ------ ROOM NAMES ------

CONTROL_ROOM_NAME = "control_room"
MAIN_ROOM_NAME = "main_room"
BATH_ROOM_NAME = "bath_room"
LABORATORY_ROOM_NAME = "laboratory_room"
GROWTH_ROOM_NAME = "growth_room"
AIRLOCK_ROOM_NAME = "airlock_room"

# ------ ITEM NAMES ------

GINGER = "ginger"
STAR_DUST = "star_dust"
TOOTH_PASTE = "tooth_paste"
CURE = "cure"
