import pygame
import random

# ------ CONSTANTS ------

# Colors
WHITE = (255, 255, 255)
BLUE = (0, 0, 255)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)
GREEN = (0, 255, 0)
BLACK = (0, 0, 0)

# ------ GAME OPTIONS ------

WIDTH, HEIGHT = 1080, 720
FRAMERATE = 60

FONT_SIZE = 36
FONT_COLOR = WHITE

PLAYER_SPEED = 500
BULLET_SPEED = 700
BOULDER_SPAWN_INTERVAL_MS = 1500
BULLET_COOLDOWN_MS = 300

VIRUS_GROWTH_KILL = 5
VIRUS_GROWTH_COOLDOWN_MS = 10000
VIRUS_GROWTH_DISPLAY_MSG_TIME_MS = 5000


# ------ ROOM NAMES ------

CONTROL_ROOM_NAME = "control_room"
MAIN_ROOM_NAME = "main_room"
BATH_ROOM_NAME = "bath_room"
LABORATORY_ROOM_NAME = "laboratory_room"
GROWTH_ROOM_NAME = "growth_room"
AIRLOCK_ROOM_NAME = "airlock_room"

